[repo]
minVersion = "v0.0.23"
url = "https://altlinux.space/aides-community/aides.git"
mirrors = [
    "https://github.com/aides-community/aides.git",
    "https://codeberg.org/aides-community/aides.git"
]