name: Update Repository

on:
  schedule:
    - cron: '0 2/6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    

jobs:
  update:
    runs-on: alt-latest
    container:
      image: altlinux.space/actions/runner/python:sisyphus
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run update script
        run: |
          python3 update.py
      - name: Check for changes
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi
          
      - name: Commit changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "Automated Update"
          git config --global user.email "aides-helper-bot@noreply.altlinux.space"
          git add -A
          git commit -m "Automated update: $(date -u +'%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git push origin HEAD
  