name: Verify checksums

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  verify-checksums:
    runs-on: alt-sisyphus
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y curl jq
      - name: Install stplr-spec
        run: |
          curl -L https://altlinux.space/stapler/stplr-utils/releases/download/v0.0.8/stplr-spec-linux-amd64 -o /usr/bin/stplr-spec
          chmod +x /usr/bin/stplr-spec
      - run: npm ci
      - name: Verify checksums
        uses: actions/forgejo-script@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const script = require('.forgejo/verify-checksums.js')
            await script({forgejo, exec})
