name: Verify checksums

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  verify-checksums:
    runs-on: alt-sisyphus
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y curl jq
      - name: Install stplr-spec
        run: |
          curl -L https://altlinux.space/stapler/stplr-utils/releases/download/v0.0.8/stplr-spec-linux-amd64 -o /usr/bin/stplr-spec
          chmod +x /usr/bin/stplr-spec

      - name: Verify checksums for all Staplerfiles
        id: verify
        shell: bash
        run: |
          failed=()
          passed=()

          for file in $(find . -type f -name Staplerfile); do
            pkg_dir=$(dirname "$file")
            pkg=$(basename "$pkg_dir")

            echo "Checking $pkg..."

            if stplr-spec verify-checksums --path "$file"; then
              passed+=("$pkg")
            else
              failed+=("$pkg")
            fi

            rm -rf $HOME/.cache/stapler-spec
          done

          failed_json=$(printf '%s\n' "${failed[@]}" | jq -R . | jq -s .)
          passed_json=$(printf '%s\n' "${passed[@]}" | jq -R . | jq -s .)

          echo "failed=$failed_json" >> $GITHUB_OUTPUT
          echo "passed=$passed_json" >> $GITHUB_OUTPUT

      - name: Report issues
        uses: actions/forgejo-script@v1
        env:
          FAILED: ${{ steps.verify.outputs.failed }}
          PASSED: ${{ steps.verify.outputs.passed }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            function sleep(ms) {
              return new Promise(r => setTimeout(r, ms));
            }

            const owner = "aides-pkgs";
            const title = "Checksum verification failed";
            const failed = JSON.parse(process.env.FAILED);
            const passed = JSON.parse(process.env.PASSED);

            console.log("Failed:", failed);
            console.log("Passed:", passed);

            for (const pkg of failed) {
              console.log(`Processing FAILED pkg: ${pkg}`);

              const issues = await forgejo.repos.issueListIssues(
                owner,
                pkg,
                {
                  state: "open",
                }
              );

              const existing = issues.data.find(i => i.title === title);

              const body = `Timestamp: ${new Date().toISOString()}`.trim();

              if (existing) {
                console.log(`Updating existing issue #${existing.number}`);
                await forgejo.repos.issueEditIssue(owner, pkg, existing.number, {
                  body: body,
                })
              } else {
                console.log("Creating new FAILED issue");
                await forgejo.repos.issueCreateIssue(owner, pkg, {
                  title: title,
                  body: body,
                })
              }

              await sleep(1500);
            }

            for (const pkg of passed) {
              console.log(`Processing PASSED pkg: ${pkg}`);

              const issues = await forgejo.repos.issueListIssues({
                owner,
                repo: pkg,
                state: "open",
              });

              const existing = issues.data.find(i => i.title === title);
              if (!existing) continue;

              console.log(`Closing issue #${existing.number}`);

              await forgejo.repos.issueEditIssue(
                owner,
                pkg,
                existing.number,
                {
                  state: "closed",
                }
              );

              await forgejo.repos.issueCreateComment({
                owner,
                repo: pkg,
                index: existing.number,
                body: `Issue resolved automatically. Package now passes checksum verification.`,
              });

              await sleep(1500);
            }
