#!/bin/bash

. "$(dirname "$0")/_common.sh"

api_res=$(curl -s $CURSOR_API_URL)

stplr-spec set-field version "$(echo $api_res | jq -r .version)"
stplr-spec set-field _commit "$(echo $api_res | jq -r .commitSha)"
stplr-spec update-checksums
