#!/usr/bin/env python3
import sys
sys.path.insert(0, '../..')

from _utils import get_field, get_etag_lastmod

import requests

url = get_field('_source_url')
old_etag = get_field('_source_etag')
old_lastmod = get_field('_source_last_modified')

resp = requests.head(url)
new_etag, new_lastmod = get_etag_lastmod(resp)

etag_changed = new_etag != old_etag
lastmod_changed = new_lastmod != old_lastmod

version = get_field('version')
new_version = version

if etag_changed or lastmod_changed:
    new_version = "new_unknown_version"

print(version, new_version)