[docker-desktop]
source = "htmlparser"
url = "https://desktop.docker.com/linux/main/amd64/appcast.xml"
xpath = "//item/title/text()"
is_xml = true
from_pattern = '(\d+\.\d+\.\d+) \((\d+)\)'
to_pattern = '\1|\2'
