# This file describes how to check for updates using nvchecker.
# For more information, visit l.aides.space/nvchecker

[antigravity]
source = "regex"
url = "https://artifactregistry.googleapis.com/v1/projects/antigravity-auto-updater-dev/locations/us-central1/repositories/antigravity-debian/files?page_size=20&order_by=update_time+desc"
regex = 'pool%2Fantigravity_([\d.]+-\d+)_amd64_'
from_pattern = '([\d.]+)-(\d+)'
to_pattern = '\1|\2'